### ISSUE TITLE
Allowing for Proxies

### ISSUE THREAD

**Issue by scsmncao** [arkadiyt/ssrf_filter#25]
Hey Arkadiy!

We're looking to send requests through a proxy and it looks like if we want to continue using this library we'll need to add proxy support. Not sure if you had any insight on this or if there's a difficult approach. Thanks!

**Comment by arkadiyt** [comment]
If you mean a socks proxy then it might be possible

If you mean a regular http proxy then wouldn't be compatible with this gem as it would introduce a time-of-check-to-time-of-use vulnerability (where the gem validates a url, then sends a request to the proxy server, which resolves the hostname to an internal IP and makes a SSRF request)

**Comment by scsmncao** [comment]
Ah I see, that makes sense, we're looking to use a regular http proxy. If that's the case, it might be better for us to fork it and make the modifications internally? Reason being that it's a proxy that we made and know exactly what's going on.

**Comment by arkadiyt** [comment]
You're welcome to fork the gem.

Just to be clear I was assuming the proxy was under your control (that's the only threat model that makes sense, otherwise the SSRF wouldn't even be your vulnerability). Even if you made the proxy, an attacker can perform SSRF by changing the DNS records on the provided url between the time you check it with the gem and when the proxy server fetches it.

**Comment by scsmncao** [comment]
Sorry about that, definitely not a security expert haha. But I see that's really good to know and super informative. In that case we might need to find some other alternative to fix this issue. Thank you!
